#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

INFRA_DIR="${INFRA_DIR:-$HOME/dev/infra}"
SENDER_DOMAIN="send.witcc.dev"
HEALTHCHECK="https://calendar.witcc.dev/healthchecks/action_mailer"

banner "Resend for the WIT calendar backend"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Resend: add the sending domain"
say "The backend sends as noreply@$SENDER_DOMAIN, so Resend has to verify"
say "that domain first. A subdomain keeps this mail's reputation separate"
say "from anything else on witcc.dev, which is Resend's own advice."
printf '\n'
open_url "https://resend.com/domains"
step "Sign in to Resend as the WIT Coding Club account."
step "Click 'Add Domain'."
step "Enter exactly: $SENDER_DOMAIN"
step "Region: North Virginia (us-east-1). It sets the MX value, so if you"
say  "  pick another region, use the value Resend then shows you."
step "Click 'Add'. Resend now shows a table of DNS records."
printf '\n'
note "Leave that table open. The next stage copies from it."
pause "Domain added and the DNS table is on screen?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: add the DNS records"
say "witcc.dev is on Cloudflare. Add the three records Resend just showed."
printf '\n'
warn "Cloudflare appends the zone to every name you type."
say  "So strip the trailing '.witcc.dev' from each name Resend shows you."
say  "Resend shows 'send.$SENDER_DOMAIN' -> you type 'send.send'."
printf '\n'
say "Expected shape, but trust the dashboard over this script:"
note "  MX   send.send                    feedback-smtp.us-east-1.amazonses.com   priority 10"
note "  TXT  send.send                    v=spf1 include:amazonses.com ~all"
note "  TXT  resend._domainkey.send       p=MIGfMA0GCSq...  (long, copy all of it)"
printf '\n'
open_url "https://dash.cloudflare.com/?to=/:account/witcc.dev/dns/records"
step "Add each record with 'Add record'. Set every one to DNS only, not proxied."
step "Copy the DKIM value in one go. It is long and wraps in the dashboard."
printf '\n'
warn "Do not touch the two records on the root:"
note "  MX  @  route1/2/3.mx.cloudflare.net        Cloudflare Email Routing, inbound mail"
note "  TXT @  v=spf1 include:_spf.mx.cloudflare.net ~all"
say  "Resend puts its SPF on the send.* subdomain, so the root stays as it is."
pause "All three records saved in Cloudflare?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Resend: verify the domain"
say "Cloudflare publishes in seconds, but Resend can take a few minutes."
printf '\n'
open_url "https://resend.com/domains"
step "Open $SENDER_DOMAIN and click 'Verify DNS Records'."
step "Wait for the status to read 'Verified'. Re-click if it says pending."
printf '\n'
note "To check the records yourself from this machine:"
note "  dig +short TXT resend._domainkey.$SENDER_DOMAIN"
note "  dig +short MX send.$SENDER_DOMAIN"
printf '\n'
if confirm "Want this script to run those two lookups now?"; then
  printf '\n'
  note "DKIM:"; dig +short TXT "resend._domainkey.$SENDER_DOMAIN" | sed 's/^/    /' || true
  note "MX:";   dig +short MX  "send.$SENDER_DOMAIN"              | sed 's/^/    /' || true
  printf '\n'
  note "Empty output means the records are not visible yet. Give it a minute."
fi
pause "Resend says Verified?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Resend: create the API key"
say "The API key doubles as the SMTP password. Rails sends it with the user"
say "name 'resend', which the app hardcodes."
printf '\n'
open_url "https://resend.com/api-keys"
step "Click 'Create API Key'."
step "Name: wit-calendar-production"
step "Permission: Sending access."
step "Domain: $SENDER_DOMAIN, so a leaked key cannot send as anything else."
step "Click 'Add', then copy the key. It starts with re_ and is shown once."
printf '\n'
warn "Copy it to your clipboard and keep it there. The next stage pastes it"
say  "  straight into the encrypted secret. This script never reads it."
pause "Key copied?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "agenix: put the key in wit-calendar-env.age"
say "alastor reads the app's environment from this encrypted file."
printf '\n'
step "The editor is about to open on the decrypted contents."
step "Add one line, then save and quit:"
printf '\n'
note "    RESEND_API_KEY=re_your_key_here"
printf '\n'
step "Leave RAILS_MASTER_KEY, CALENDAR_DATABASE_PASSWORD and POSTGRES_PASSWORD"
say  "  exactly as they are."
printf '\n'
pause "Ready to open the editor?"
if ! ( cd "$INFRA_DIR/secrets" && agenix -e wit-calendar-env.age ); then
  warn "agenix exited with an error. Nothing was written."
  SKIPPED+=("RESEND_API_KEY in wit-calendar-env.age: agenix failed")
fi
printf '\n'
if git -C "$INFRA_DIR" diff --quiet -- secrets/wit-calendar-env.age; then
  warn "wit-calendar-env.age is unchanged. Did the edit save?"
  SKIPPED+=("RESEND_API_KEY in wit-calendar-env.age: file was not modified")
else
  printf '  %s✓%s wit-calendar-env.age re-encrypted\n' "$GREEN" "$RESET"
  say "Commit it, because the deploy reads the git tree:"
  note "  cd $INFRA_DIR && git add secrets/wit-calendar-env.age"
  note "  git commit -m 'chore: add RESEND_API_KEY to wit-calendar env'"
fi
pause "Secret saved?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Merge the two PRs, then deploy"
say "Two changes are waiting. The Rails one is what actually sends the mail."
printf '\n'
step "calendar-backend: the Resend SMTP config."
open_url "https://github.com/WITCodingClub/calendar-backend/pulls"
step "infra: the docs saying the env file now needs RESEND_API_KEY."
open_url "https://github.com/jaspermayone/infra/pulls"
printf '\n'
say "Merging calendar-backend to main builds an image and restarts the app"
say "on alastor by itself. The secret needs a NixOS rebuild as well:"
printf '\n'
note "  cd $INFRA_DIR && deploy .#alastor"
note "  ssh alastor sudo systemctl restart wit-calendar-web"
printf '\n'
warn "Deploy alastor only after the agenix commit, or the container starts"
say  "  without the key and every send fails auth."
pause "Both merged, alastor deployed, web service restarted?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Confirm that mail actually goes out"
say "The app has a health check that opens an SMTP connection."
printf '\n'
note "  curl -s $HEALTHCHECK"
printf '\n'
if confirm "Run it now?"; then
  printf '\n'
  curl -s --max-time 20 "$HEALTHCHECK" | sed 's/^/    /' || warn "the request failed"
  printf '\n'
  note "PASSED means Rails reached smtp.resend.com."
  note "Still 'localhost:25' means the new image is not running yet."
fi
printf '\n'
say "Then send one real message end to end:"
step "Open the sign-in page and use 'Forgot your password?' on your own account."
open_url "https://calendar.witcc.dev/users/sign_in"
step "Watch it land in Resend's log, and check the inbox."
open_url "https://resend.com/emails"
printf '\n'
note "A friend request also sends mail now, once PR #557 is merged."
pause "Mail received?"

finish
